### PR TITLE
Adding carusel to comments section

### PR DESCRIPTION
**Pull request by nasik87**

### CODE REVIEW

**Comment by AlexMihov** [comment]
Please remove "node_modules" and "bower_components" from the request; Else I can't see the diff :)

add them to the ".gitignore"... google it or ask me :)

Additionally: please make the arrows look a bit fancier... they are a bit small for my taste. Same for the little dots under the carussel... make them bigger, so that it's easy to click them

**Comment by nasik87** [comment]
I left the folder bower_components/slick-carousel out of .gitignore since I made some changes on the css files in it

**Comment by AlexMihov** [comment]
still some bower components in the repo :)

**Comment by nasik87** [comment]
@AlexMihov Should be removed now!

**Pull request merged**
